import type { ReportProducer } from "./daily-report";

/** Placeholder until the email + Grok producer exists. */
export const stubProducer: ReportProducer = async () => ({
  emailsRead: 0,
  needsReply: 0,
  billsDue: 0,
  archived: 0,
  summary: "Email source not yet connected. This report was generated by the stub producer.",
  items: [],
});
